[BYBIT]
api_public=
api_secret=
;ТИКЕРЫ ЧЕРЕЗ ЗАПЯТУЮ
tickers=BTC/USDT:USDT
[INDICATOR]
; 15m, 30m, 1h, 4h - только такие таймфреймы
timeframe=15m
obv_length=1
macd_fast=12
macd_slow=26
macd_signal=9
stoch_k=14
stoch_d=3
stoch_smooth=1
; Не больше 200
sma_lenght=200
; Не трогать
period=300
[INDICATOR.WEIGHTS]
; Дробный величины указываются через точку
macd=2
stochastic=2
obv=2
ma=2
vol=2
[ORDER]
; volume_const указывается в BTC
volume_const=0.01
; 10% для примера
volume_percent=50
leverage=10