[BYBIT]
api_public=
api_secret=
[INDICATOR]
; 15m, 30m, 1h, 4h - только такие таймфреймы
timeframe=15m
obv_length=1
macd_fast=12
macd_slow=26
macd_signal=9
stoch_k=14
stoch_d=3
stoch_smooth=1
sma_lenght=200
; Не трогать
period=300
[INDICATOR.WEIGHTS]
macd=
stochastic=
obv=
ma=
vol=
[ORDER]
; volume_const указывается в BTC
volume_const=0.0015
; 10% для примера
volume_percent=10
leverage=10